### ISSUE TITLE
Unexpected inference result on custom dataset

### ISSUE THREAD

**Issue by chenzhaiyu** [foamliu/Deep-Image-Matting#22]
Hi,

I used the pretrained weights to test on my own building dataset. Here are some examples of input patches, trimaps and corresponding predictions.

![deep_matting_result](https://user-images.githubusercontent.com/24312770/50819608-807fe200-1365-11e9-8c63-36288a291d3c.png)

Even if the pretrained model never fine-tuned on my dataset, I didn't expect its prediction to have such jagged edges (which shapes like the gray part in the trimaps). What could have gone wrong?

**Comment by wangxin1233** [comment]
Hi,
I am also working on this model. Can I add a WeChat to ask some questions?

**Comment by chenzhaiyu** [comment]
> Hi,
> I am also working on this model. Can I add a WeChat to ask some questions?

Sure, my WeChat ID is "woecat".

**Comment by foamliu** [comment]
Hello realczy, thanks for the feedback. Are you using test.py, I've just fixed an issue, can you have a try again?

**Comment by chenzhaiyu** [comment]
I tried test.py and the jagged edges still existed in predictions. I could only blame dataset bias for the abnormal performance.

**Comment by foamliu** [comment]
Thanks @realczy , could you paste new prediction image so I can take a look?

**Comment by generalmilk** [comment]
Looks like you have resized the trimap with interpolation.
